default_type = "application/octet-stream"
[types]
wasm = "application/wasm"

[[host]]
ip = "0.0.0.0"
port = 4000
timeout = 15

[host.headers]
X-Powered-By = "candy"

[[host.route]]
index = ["index.html"]
location = "/"
root = "./html"
[host.route.error_page]
status = 404
page = "404.html"

[[host.route]]
index = ["index.html"]
location = "/candy/"
root = "./docs/build"
[host.route.error_page]
status = 404
page = "404.html"

[[host.route]]
location = "/proxy/"
proxy_pass = "http://localhost:3000/"
proxy_timeout = 10
