default_type = "application/octet-stream"
[types]
wasm = "application/wasm"

[[host]]
ip = "0.0.0.0"
port = 4000
keep_alive = 15

[host.headers]
X-Powered-By = "candy"

[[host.route]]
index = ["index.html"]
location = "/"
root = "./html"
[host.route.error_page]
status = 500
page = "404.html"

[[host.route]]
index = ["index.html"]
location = "/www/"
root = "./html"
[host.route.error_page]
status = 500
page = "404.html"

[[host.route]]
index = ["index.html"]
location = "/www/test/"
root = "./html"
