# mime
default_type = "application/octet-stream"
# add mime types
[types]
wasm = "application/wasm"
[[host]]
ip = "0.0.0.0"
port = 4000
# index file name and format
index = ["index.html"]
# http keep alive timeout
keep_alive = 75
# http process max timeout
process_timeout = 15
[[host.route]]
# route path: GET /
location = "/"
# static file path
root = "./html"
