[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]
dependencies = ["fix"]

[tasks.fix]
command = "cargo"
args = ["fix", "--allow-dirty", "--all-features"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.dev]
command = "cargo"
args = ["watch", "-x", "'run'"]
