### GET request with a header
GET http://localhost:4000/
Accept: application/json

### Send POST request with json body
POST http://localhost:4000/
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}
