# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docs CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        


    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      uses: pnpm/action-setup@v4.1.0
      #with:
        # Version of pnpm to install
        # version: # optional
        # Where to store pnpm files
        #dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
        #run_install: # optional, default is null
        # File path to the package.json to read "packageManager" configuration
        #package_json_file: # optional, default is package.json
        # When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
        #standalone: # optional, default is false
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm build
